#!/usr/bin/env bash
set -euo pipefail
mkdir -p games
./extract-games-from-leagues.py leagues/* | jq -r '.[] | .boxscore_url' | sort | uniq > ./boxscore-urls
while read url; do
  echo "Downloading $url ..."
  wget "$url"
  for i in `seq 10`; do echo -n "$i... "; sleep 1; done
  echo
done < ./boxscore-urls
